version: '2.2'

services:

  rabbit:
    image: rabbitmq:3.8-management-alpine
    ports:
      # Expose the RabbitMQ management UI
      - 15672:15672
    depends_on:
      - postgres
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit

  postgres:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dagster_celery
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5


  minio:
    image: minio/minio:RELEASE.2020-08-16T18-39-38Z
    ports:
      - '9000:9000'
    volumes:
      - ./.minio:/data
      - ./data:/data_ppl
    depends_on:
      - postgres
    environment:
      MINIO_ACCESS_KEY: 'minio'
      MINIO_SECRET_KEY: 'miniosecret'
    command: 'server /data'
     
  flower: 
    image: mher/flower:0.9.5
    ports:
      - 5555:5555
    depends_on:
      - postgres
    command: flower --port=5555 --broker=amqp://rabbit:rabbit@rabbit:5672//

  # generic worker
  worker-generic:
    build: .
    image: dagster-celery-worker
    volumes:
      - ./workflows:/app
      - ./data:/data_ppl
    depends_on:
      - postgres
    entrypoint: "dagster-celery worker start --loglevel=info --app=dagster_celery.app -y celeryconfig.yaml --name generic-worker"
    environment: 
      DAGSTER_HOME: /app
    scale: 2

  # GPU worker (doesn't really use the GPU, just demonstrates worker selection from solids)
  worker-gpu:
    build: .
    image: dagster-celery-worker
    volumes:
      - ./workflows:/app
      - ./data:/data_ppl
    depends_on:
      - postgres
    entrypoint: "dagster-celery worker start --loglevel=info --app=dagster_celery.app -y celeryconfig.yaml -q gpu --name gpu-worker"
    environment: 
      DAGSTER_HOME: /app

  dagit:
    build: .
    image: dagster-celery-worker # Use the worker image for convenience
    ports:
      - 3000:3000 # Dagit
    volumes:
      - ./workflows:/app
      - ./data:/data_ppl
    depends_on:
      - postgres
    entrypoint: dagit --host 0.0.0.0 -f dagster_pipeline.py
    environment: 
      DAGSTER_HOME: /app

